---
# Shared definition block
# This is where you would define any attributes that all your jobs will
# inherit.
shared:
  # We specify a common NodeJS Docker image for our Jobs. It takes the form of
  # "repo_name:tag_label", where the "tag_label" is optional.
  # Docker image - https://hub.docker.com/r/library/node/
  image: node:6

subscribe: 
  scmUrls:
    - git@github.com:supra08/functional-workflow.git: ['~push', '~pr']

# Jobs definition block
# All pipelines have "main" by default, and is implicitly defined.
jobs:
  # We explicitly define "main" in our configuration so that it does what we want
  # it to do.
#   main:
#     requires: [~pr, ~commit, ~subscribe]
#     steps:
#       - install: npm install
#       - test: npm test
#   publish:
#     requires: main
#     steps:
#       - set_access: npm config set access public > /dev/null 2>&1
#       - set_token: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN > /dev/null 2>&1
#       - publish_npm: npm publish
#     secrets:
#       - NPM_TOKEN
  SIMPLE:
      steps:
          - echo: echo test
      requires: [~pr, ~commit, ~subscribe]
  PARALLEL1:
      steps:
          - echo: echo test
      requires: [SIMPLE]
  PARALLEL2:
      steps:
          - echo: echo test
      requires: [SIMPLE]
  JOIN:
      steps:
          - echo: echo test
      requires: [PARALLEL1, PARALLEL2]
